### ISSUE TITLE
Bug: Events aren't resetting

### ISSUE THREAD

**Issue by Larinitus** [allenjiang17/theSearchForEden#29]
Something happened in the last 24 hour that has been making events not work properly. If I am in Event A that auto-triggers another Event B, and then if I leave and come back, I stay at Event B, not Event A.

So for example, if I grab a Fig Leaf off the fig leaf tree, and then leave and come back to it, I just get the successful fig leaf grab event, and I can't grab anymore fig leaves.

**Comment by Larinitus** [comment]
I am guessing this might have to do with the Event update from last night regarding the tailor quest. So we need a way to ensure that things like the tailor quest doesn't reset, but also need a way to make sure that other events do reset.

**Comment by allenjiang17** [comment]
Yeah i'll get to this tonight. I need to rethink and rework the whole event system. I changed it so that we save current events at a location. Otherwise the tailor location is an insanely long chain from the initial event that takes you all the way through quest 1 and quest if you're on quest 2.

**Comment by Larinitus** [comment]
What if we have a separate .js file that's similar to items.js., except that it tracks storyline progress instead of items? So we can have an object for example called "craftyProgress" that starts at 0. And then once you get the Fig Leaves, we can change it to 1. And once you get the Garment of Skin, we can change it to 2. And every time we launch the Crafty event, we have if statements that determine which sub-events to launch.

**Comment by allenjiang17** [comment]
We have this already, it's the Map object in the gameState. it's not a js file because it's not a static data structure, it's dependent on the player. 

The only thing is right now it tracks and stores the current event for a location. but thats the problem -- there are some places, like the fig tree, where we don't want it to save the current event (it moved onto the result event, etc). So I'm going to change it so it doesn't auto update the current event for each location, but only in places we specify

**Comment by allenjiang17** [comment]
Fixed.
